### ISSUE TITLE
NuGet Gallery

### ISSUE THREAD

**Issue by phillipsj** [cake-contrib/Cake.Chutzpah#1]
Can we get this posted to Nuget?  Is it fully functional?

**Comment by jrnail23** [comment]
Sure, I can publish it this weekend.  It works fine for me, and I haven't really come across any problems with it.

**Comment by gep13** [comment]
@phillipsj as you will hopefully notice, this repo has been moved under the cake-contrib organisation.  I will hopefully get an initial release out over the weekend.  Feel free to bug me if you don't see anything going out.

**Comment by gep13** [comment]
@phillipsj I have pushed the 0.0.3 version to NuGet, just so that we have got a baseline to work from.  We can start updating this from here.
