### ISSUE TITLE
Error executing Chutzpah

### ISSUE THREAD

**Issue by phillipsj** [cake-contrib/Cake.Chutzpah#2]
I am receiving this error:
# 
# Chutzpah

Executing task: Chutzpah
An error occured when executing task.
Error: Method not found: 'Cake.Core.IO.ProcessArgumentBuilder Cake.Core.ProcessArgumentListExtensions.Append(Cake.Core.IO.ProcessArgumentBuilder, System.String, System.Object[])'.

It is related to line 137 in ChutzpahRunner.cs.  If I change that line to not use the string.format method and just do the command individually it runs perfectly fine.  I would say this is an issue in Cake, but I wanted to post it here first.

**Comment by jrnail23** [comment]
@phillipsj, which versions of Cake and/or Cake.Core packages are you running?

**Comment by phillipsj** [comment]
@jrnail23 Cake and Cake Core 0.5.5 

I do not think the MaxParallelism property is getting set.  If null I can reproduce the error with a unit test.  The documentation said it gets defaulted to 1, but I do not see it getting set at all.

**Comment by jrnail23** [comment]
I think that might actually be Chutzpah's default (if unset).  I'm on the road right now though.

—

**Comment by phillipsj** [comment]
Thanks for the quick responses.  Hopefully I can get this figured out.  I make that once source change and it runs beautifully.  Thanks for creating this addin.

**Comment by jrnail23** [comment]
You bet.  Glad to see someone getting some use out of it! :smile:

—
