### ISSUE TITLE
Setup convention based build

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Chutzpah#5]
So it is the same as other repos in this organisation.

**Comment by gep13** [comment]
@phillipsj just about ready to release, but I am getting a build error when trying to run xUnit:

https://ci.appveyor.com/project/cakecontrib/cake-chutzpah/build/0.1.0-unstable.4.build.5#L563

If you have any insights on why this might be happening, I would love to here it 😄 

Thanks!

**Comment by phillipsj** [comment]
I will take a look.

**Comment by phillipsj** [comment]
@gep13 So after pulling down your latest changes, I can no longer get the project to build using visual studio.

Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\gep13.ApplicationRunner.0.1.2\build\gep13.ApplicationRunner.targets.	Cake.Chutzpah	C:\Users\cphil\code\Cake.Chutzpah\src\Cake.Chutzpah\Cake.Chutzpah.csproj	75	


Error		NuGet Package restore failed for project Cake.Chutzpah.Tests: Unable to find version '0.1.1' of package 'gep13.xUnitRunner'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'gep13.xUnitRunner.0.1.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'gep13.xUnitRunner.0.1.1' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'gep13.xUnitRunner.0.1.1' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
  https://www.myget.org/F/extra-build-packages/api/v3/index.json: Package 'gep13.xUnitRunner.0.1.1' is not found on source 'https://www.myget.org/F/extra-build-packages/api/v3/index.json'.
.			0

**Comment by phillipsj** [comment]
I am now also getting the same error as AppVeyor when I run Cake on my machine.

**Comment by phillipsj** [comment]
@gep13 I got it to build locally for me.  I basically removed all the Nuget packages for the testing project and added them back.  When I did this I got an app.config added with a binding redirect.

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="xunit.core" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.1.0.3179" newVersion="2.1.0.3179" />
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
    </configuration>

**Comment by phillipsj** [comment]
Now it seems there is an issue with the xUnit runner that cake is using.

Executing: C:\Users\cphil\code\Cake.Chutzpah\tools\xunit.runner.console\tools\xunit.console.exe
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
System.IO.FileNotFoundException: Could not load file or assembly 'xunit.core, Version=2.0.0.2929, Cu
cKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.

**Comment by gep13** [comment]
>@phillipsj said...
So after pulling down your latest changes, I can no longer get the project to build using visual studio.

Due to the current version of Cake.Recipe, you need to run `build.ps1` first, in order to restore all the packages that are required.  This will be going away in a future version of Cake.Recipe, so the initial build works out of Visual Studio.

I never had an issue running the tests out of Visual Studio, that always worked for me.  Are you saying that this wasn't working for you initially?

Ok, so we are back to the same place then.  Will keep digging into this to see if I can find anything.

**Comment by phillipsj** [comment]
Ok and yes the tests did not work for me.

**Comment by gep13** [comment]
Which test runner do you use within Visual Studio?

**Comment by gep13** [comment]
@phillipsj ok, looks like I have got this working 😄
